### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by s2cocos2** [soon91/blog-backend-server#1]
주석이 잘 작성되어 있어 코드를 볼 때 이해하기 쉬웠다.
BlogService.java의 updateBlog와 deleteBlog의 메서드에서 비밀번호 일치여부를 확인하는 코드가 중복된다. 코드의 재사용성을 위해 따로 메서드를 작성하면 좋을 것 같다고 생각한다.

**Comment by soon91** [comment]
넵 감사합니다! 중복 코드를 줄이니 훨씬 더 코드가 보기 좋네요!!
